template: native
provider: command
major-version: 0
pulumiVersionFile: .pulumi.version
providerDefaultBranch: main
parallel: 3
timeout: 0.0000001
noSchema: true # Disable schema check.
envOverride:
    PULUMI_API: https://api.pulumi-staging.io
esc:
    enabled: true
