template: native
provider: command
major-version: 0
aws: true
pulumiVersionFile: .pulumi.version
providerDefaultBranch: main
parallel: 3
timeout: 0.0000001
envOverride:
  AWS_REGION: us-west-2
  PULUMI_API: https://api.pulumi-staging.io
